### ISSUE TITLE
Fix usage of properties

### ISSUE THREAD

**Issue by TheDoomLord** [d00mlord/SocketHandler#1]
client.cs has an IsRunning property and an isRunning variable.

variables like isRunning should be declared with an underscore in addition to being private.

IsRunning should be two functions instead of a property. A usual dev flow would be to search the class for a Shutdown() function. It's not obvious that setting IsRunning to false is the way to do this.

There may be other instances of property abuse in this module.

**Comment by JeremyGagnier** [comment]
Fixed
